import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { compileReportLayout } from './layout.mjs';
import {
  escapeAttribute,
  escapeHtml,
  jsonForHtml,
  safeHref,
  sha256Text,
} from './utils.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BASE_CSS = fs.readFileSync(path.join(__dirname, '..', 'assets', 'report-base.css'), 'utf8');
const RUNTIME_JS = fs.readFileSync(path.join(__dirname, '..', 'assets', 'report-runtime.js'), 'utf8');

const LABELS = {
  'zh-CN': {
    answer: '核心结论',
    scope: '范围',
    implications: '影响',
    nextAction: '下一步',
    evidence: '证据',
    owner: '负责人',
    date: '时间',
    recommended: '建议方案',
    sources: '证据与来源',
    criterion: '评估维度',
    overview: '概述',
    dark: '深色',
    light: '浅色',
    print: '打印',
    generated: '由 Reportify 确定性生成',
    visualPending: '自动检查不替代截图审美复核',
    archetypes: { status: '状态汇报', decision: '决策简报', research: '研究摘要' },
    audiences: { executive: '管理层', technical: '技术读者', mixed: '混合读者' },
    statuses: {
      done: '已完成',
      'in-progress': '进行中',
      blocked: '阻塞',
      planned: '计划中',
      good: '正常',
      warning: '关注',
      risk: '风险',
      neutral: '中性',
    },
  },
  en: {
    answer: 'Answer',
    scope: 'Scope',
    implications: 'Implications',
    nextAction: 'Next action',
    evidence: 'Evidence',
    owner: 'Owner',
    date: 'Date',
    recommended: 'Recommended',
    sources: 'Evidence and sources',
    criterion: 'Criterion',
    overview: 'Overview',
    dark: 'Dark',
    light: 'Light',
    print: 'Print',
    generated: 'Deterministically generated by Reportify',
    visualPending: 'Automated checks do not replace screenshot review',
    archetypes: { status: 'Status report', decision: 'Decision brief', research: 'Research summary' },
    audiences: { executive: 'Executive', technical: 'Technical', mixed: 'Mixed audience' },
    statuses: {
      done: 'Done',
      'in-progress': 'In progress',
      blocked: 'Blocked',
      planned: 'Planned',
      good: 'Good',
      warning: 'Watch',
      risk: 'Risk',
      neutral: 'Neutral',
    },
  },
};

function renderStatus(status, labels) {
  if (!status) return '';
  return `<span class="status-pill" data-status="${escapeAttribute(status)}">${escapeHtml(labels.statuses[status] || status)}</span>`;
}

function renderPriority(priority) {
  if (!priority) return '';
  return `<span class="priority-pill" data-priority="${escapeAttribute(priority)}">${escapeHtml(priority)}</span>`;
}

function renderEvidence(ref, sources, labels) {
  if (!ref || !sources.has(ref)) return '';
  return `<a class="evidence-link" href="#source-${escapeAttribute(ref)}">${escapeHtml(labels.evidence)} ↘</a>`;
}

function renderMeta(item, sources, labels) {
  const parts = [];
  if (item.status) parts.push(renderStatus(item.status, labels));
  if (item.priority) parts.push(renderPriority(item.priority));
  if (item.owner) parts.push(`<span class="meta-pill">${escapeHtml(labels.owner)} · ${escapeHtml(item.owner)}</span>`);
  if (item.date) parts.push(`<span class="meta-pill">${escapeHtml(labels.date)} · ${escapeHtml(item.date)}</span>`);
  if (item.recommended) parts.push(`<span class="recommendation-pill">${escapeHtml(labels.recommended)}</span>`);
  if (item.evidence_ref) parts.push(renderEvidence(item.evidence_ref, sources, labels));
  return parts.length ? `<div class="card-meta">${parts.join('')}</div>` : '';
}

function renderDetails(details) {
  if (!Array.isArray(details) || details.length === 0) return '';
  return `<ul class="detail-list">${details.map((detail) => `<li data-check-text>${escapeHtml(detail)}</li>`).join('')}</ul>`;
}

function renderCard(item, section, sources, labels) {
  const subject = `section:${section.id}/item:${item.id}`;
  return `
    <article class="report-card" data-report-block data-geometry-box data-fill-policy="balanced" data-audit-subject="${escapeAttribute(subject)}" data-emphasis="${item.emphasis ? 'true' : 'false'}">
      <h3 data-check-text data-audit-subject="${escapeAttribute(`${subject}/title`)}">${escapeHtml(item.title)}</h3>
      <div class="block-content" data-block-content>
        ${item.summary ? `<p class="card-summary" data-check-text>${escapeHtml(item.summary)}</p>` : ''}
        ${renderDetails(item.details)}
        ${renderMeta(item, sources, labels)}
      </div>
    </article>`;
}

function renderCompactStrip(item, section, sources, labels) {
  const subject = `section:${section.id}/item:${item.id}`;
  return `
    <article class="compact-strip" data-report-block data-geometry-box data-fill-policy="balanced" data-audit-subject="${escapeAttribute(subject)}">
      <div>
        <h3 data-check-text>${escapeHtml(item.title)}</h3>
        ${renderMeta({ ...item, summary: undefined, details: undefined }, sources, labels)}
      </div>
      <div class="block-content" data-block-content>
        ${item.summary ? `<p class="card-summary" data-check-text>${escapeHtml(item.summary)}</p>` : ''}
        ${renderDetails(item.details)}
      </div>
    </article>`;
}

function renderCompactRow(item, section, index, sources, labels) {
  const subject = `section:${section.id}/item:${item.id}`;
  const prefix = section.kind === 'findings'
    ? `<span class="finding-index">${String(index + 1).padStart(2, '0')}</span>`
    : section.kind === 'actions'
      ? `<span class="action-index">${String(index + 1).padStart(2, '0')}</span>`
      : '';
  const metaParts = [];
  if (item.status) metaParts.push(renderStatus(item.status, labels));
  if (item.priority) metaParts.push(renderPriority(item.priority));
  if (item.owner) metaParts.push(`<span class="meta-pill">${escapeHtml(labels.owner)} · ${escapeHtml(item.owner)}</span>`);
  if (item.date) metaParts.push(`<span class="meta-pill">${escapeHtml(labels.date)} · ${escapeHtml(item.date)}</span>`);
  if (item.evidence_ref) metaParts.push(renderEvidence(item.evidence_ref, sources, labels));
  return `
    <article class="compact-row" data-report-block data-geometry-box data-fill-policy="balanced" data-audit-subject="${escapeAttribute(subject)}">
      <div class="row-title" data-check-text>${prefix}${escapeHtml(item.title)}</div>
      <div class="row-body" data-block-content>
        ${item.summary ? `<p data-check-text>${escapeHtml(item.summary)}</p>` : ''}
        ${renderDetails(item.details)}
      </div>
      <div class="row-meta">${metaParts.join('')}</div>
    </article>`;
}

function renderCardLikeSection(section, layout, sources, labels) {
  const items = section.items || [];
  if (layout.layout === 'compact-strip') {
    return renderCompactStrip(items[0], section, sources, labels);
  }
  if (layout.layout === 'compact-list') {
    return `<div class="compact-list">${items.map((item, index) => renderCompactRow(item, section, index, sources, labels)).join('')}</div>`;
  }
  if (layout.layout === 'featured-stack') {
    const featuredIndex = layout.featuredIndex ?? 0;
    const featured = items[featuredIndex];
    const side = items.filter((_, index) => index !== featuredIndex);
    return `
      <div class="featured-layout">
        <div class="featured-main">${renderCard({ ...featured, emphasis: true }, section, sources, labels)}</div>
        <div class="featured-side">${side.map((item) => renderCard(item, section, sources, labels)).join('')}</div>
      </div>`;
  }

  const className = layout.layout === 'two-column'
    ? 'layout-two-column'
    : layout.layout === 'three-column'
      ? 'layout-three-column'
      : 'card-grid';
  return `<div class="${className}">${items.map((item) => renderCard(item, section, sources, labels)).join('')}</div>`;
}

function renderComparison(section, layout, sources, labels) {
  const items = section.items || [];
  const criteria = section.criteria || [];
  if (layout.layout === 'cards') {
    return `
      <div class="comparison-card-grid" data-equal-height-group data-audit-subject="section:${escapeAttribute(section.id)}/comparison">
        ${items.map((item) => {
          const subject = `section:${section.id}/item:${item.id}`;
          return `
            <article class="report-card" data-report-block data-geometry-box data-fill-policy="balanced" data-audit-subject="${escapeAttribute(subject)}" data-emphasis="${item.recommended ? 'true' : 'false'}">
              <h3 data-check-text>${escapeHtml(item.title)}</h3>
              <div class="block-content" data-block-content>
                ${item.recommended ? `<span class="recommendation-pill">${escapeHtml(labels.recommended)}</span>` : ''}
                ${item.summary ? `<p class="card-summary" data-check-text>${escapeHtml(item.summary)}</p>` : ''}
                <dl class="comparison-values">
                  ${criteria.map((criterion) => `<div><dt>${escapeHtml(criterion.label)}</dt><dd>${escapeHtml(item.values?.[criterion.id] ?? '—')}</dd></div>`).join('')}
                </dl>
                ${renderMeta({ ...item, recommended: false }, sources, labels)}
              </div>
            </article>`;
        }).join('')}
      </div>`;
  }

  const summaryRow = items.some((item) => item.summary)
    ? `<tr><th scope="row">${escapeHtml(labels.overview)}</th>${items.map((item) => `<td>${escapeHtml(item.summary || '—')}</td>`).join('')}</tr>`
    : '';

  return `
    <div class="table-wrap" data-report-block data-geometry-box data-fill-policy="sparse-ok" data-audit-subject="section:${escapeAttribute(section.id)}/comparison-table">
      <table>
        <thead>
          <tr>
            <th scope="col">${escapeHtml(labels.criterion)}</th>
            ${items.map((item) => `<th scope="col">${escapeHtml(item.title)}${item.recommended ? `<br><span class="recommendation-pill">${escapeHtml(labels.recommended)}</span>` : ''}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${summaryRow}
          ${criteria.map((criterion) => `
            <tr>
              <th scope="row"><span class="cell-primary">${escapeHtml(criterion.label)}</span>${criterion.description ? `<br><span class="section-note">${escapeHtml(criterion.description)}</span>` : ''}</th>
              ${items.map((item) => `<td>${escapeHtml(item.values?.[criterion.id] ?? '—')}</td>`).join('')}
            </tr>`).join('')}
        </tbody>
      </table>
    </div>`;
}

function renderTimeline(section, sources, labels) {
  return `
    <div class="timeline">
      ${(section.items || []).map((item) => `
        <article class="timeline-item" data-geometry-box data-audit-subject="section:${escapeAttribute(section.id)}/item:${escapeAttribute(item.id)}">
          ${item.date ? `<div class="timeline-date">${escapeHtml(item.date)}</div>` : ''}
          <h3 data-check-text>${escapeHtml(item.title)}</h3>
          ${item.summary ? `<p data-check-text>${escapeHtml(item.summary)}</p>` : ''}
          ${renderDetails(item.details)}
          ${renderMeta(item, sources, labels)}
        </article>`).join('')}
    </div>`;
}

function renderTable(section) {
  const columns = section.columns || [];
  const rows = section.rows || [];
  return `
    <div class="table-wrap" data-report-block data-geometry-box data-fill-policy="sparse-ok" data-audit-subject="section:${escapeAttribute(section.id)}/table">
      <table>
        <thead><tr>${columns.map((column) => `<th scope="col" style="text-align:${escapeAttribute(column.align || 'left')}">${escapeHtml(column.label)}</th>`).join('')}</tr></thead>
        <tbody>
          ${rows.map((row) => `<tr>${columns.map((column, index) => `<td${index === 0 ? ' class="cell-primary"' : ''} style="text-align:${escapeAttribute(column.align || 'left')}">${escapeHtml(row[column.key] ?? '—')}</td>`).join('')}</tr>`).join('')}
        </tbody>
      </table>
    </div>`;
}

function renderFlow(section) {
  const items = section.items || [];
  return `<div class="flow">${items.map((item, index) => `
    <article class="flow-step" data-report-block data-geometry-box data-fill-policy="balanced" data-audit-subject="section:${escapeAttribute(section.id)}/item:${escapeAttribute(item.id)}">
      <div class="block-content" data-block-content>
        <span class="step-number">${String(index + 1).padStart(2, '0')}</span>
        <h3 data-check-text>${escapeHtml(item.title)}</h3>
        ${item.summary ? `<p data-check-text>${escapeHtml(item.summary)}</p>` : ''}
        ${renderDetails(item.details)}
      </div>
    </article>${index < items.length - 1 ? '<span class="flow-arrow" aria-hidden="true">→</span>' : ''}`).join('')}</div>`;
}

function renderText(section) {
  const paragraphs = String(section.content || '')
    .split(/\n\s*\n/)
    .map((entry) => entry.trim())
    .filter(Boolean);
  return `
    <article class="prose-block" data-report-block data-geometry-box data-fill-policy="balanced" data-audit-subject="section:${escapeAttribute(section.id)}/prose">
      <div class="block-content" data-block-content>
        ${paragraphs.map((paragraph) => `<p data-check-text>${escapeHtml(paragraph)}</p>`).join('')}
        ${Array.isArray(section.bullets) && section.bullets.length ? `<ul>${section.bullets.map((bullet) => `<li data-check-text>${escapeHtml(bullet)}</li>`).join('')}</ul>` : ''}
      </div>
    </article>`;
}

function renderSection(section, layout, sources, labels) {
  let body;
  switch (section.kind) {
    case 'summary':
    case 'status':
    case 'findings':
    case 'actions':
      body = renderCardLikeSection(section, layout, sources, labels);
      break;
    case 'comparison':
      body = renderComparison(section, layout, sources, labels);
      break;
    case 'timeline':
      body = renderTimeline(section, sources, labels);
      break;
    case 'table':
      body = renderTable(section);
      break;
    case 'flow':
      body = renderFlow(section);
      break;
    case 'text':
      body = renderText(section);
      break;
    default:
      body = '';
  }

  return `
    <section id="${escapeAttribute(section.id)}" class="report-section" data-report-section data-kind="${escapeAttribute(section.kind)}" data-layout="${escapeAttribute(layout.layout)}">
      <div class="section-heading">
        <h2 data-check-text>${escapeHtml(section.title)}</h2>
        ${section.note ? `<span class="section-note" data-check-text>${escapeHtml(section.note)}</span>` : ''}
      </div>
      <div data-section-content>${body}</div>
    </section>`;
}

function renderSources(spec, labels) {
  if (!spec.sources.length) return '';
  return `
    <section id="sources" class="report-section" data-report-section data-kind="sources" data-layout="list">
      <div class="section-heading"><h2>${escapeHtml(labels.sources)}</h2></div>
      <div data-section-content>
        <ol class="sources-ledger">
          ${spec.sources.map((source) => {
            const href = safeHref(source.location);
            return `<li id="source-${escapeAttribute(source.id)}" class="source-entry" data-geometry-box>
              <span class="source-label">${escapeHtml(source.label)}</span>
              ${href
                ? `<a class="source-location" href="${escapeAttribute(href)}" rel="noreferrer">${escapeHtml(source.location)}</a>`
                : `<span class="source-location long-token">${escapeHtml(source.location)}</span>`}
              ${source.note ? `<p class="source-note">${escapeHtml(source.note)}</p>` : ''}
            </li>`;
          }).join('')}
        </ol>
      </div>
    </section>`;
}

function renderExecutive(spec, labels) {
  const executive = spec.executive || {};
  const implicationItems = executive.implications || [];
  const hasSecondary = executive.scope || implicationItems.length || executive.next_action;
  return `
    ${executive.answer ? `<div class="executive-answer" data-report-block data-fill-policy="sparse-ok" data-audit-subject="executive-answer"><span class="label">${escapeHtml(labels.answer)}</span><p data-check-text>${escapeHtml(executive.answer)}</p></div>` : ''}
    ${hasSecondary ? `<div class="executive-grid">
      ${executive.scope ? `<div class="executive-field" data-geometry-box><span class="label">${escapeHtml(labels.scope)}</span><p data-check-text>${escapeHtml(executive.scope)}</p></div>` : ''}
      ${implicationItems.length ? `<div class="executive-field" data-geometry-box><span class="label">${escapeHtml(labels.implications)}</span><ul>${implicationItems.map((entry) => `<li data-check-text>${escapeHtml(entry)}</li>`).join('')}</ul></div>` : ''}
      ${executive.next_action ? `<div class="executive-field" data-geometry-box><span class="label">${escapeHtml(labels.nextAction)}</span><p data-check-text>${escapeHtml(executive.next_action)}</p></div>` : ''}
    </div>` : ''}`;
}

function renderMetrics(spec, sources, labels) {
  if (!spec.metrics.length) return '';
  return `<aside class="hero-metrics" aria-label="Metrics">
    ${spec.metrics.map((metric) => `<article class="metric-card" data-report-block data-geometry-box data-fill-policy="sparse-ok" data-audit-subject="metric:${escapeAttribute(metric.id)}" data-status="${escapeAttribute(metric.status || 'neutral')}">
      <div class="block-content" data-block-content>
        <span class="metric-value" data-check-text>${escapeHtml(metric.value)}</span>
        <span class="metric-label" data-check-text>${escapeHtml(metric.label)}</span>
        ${metric.evidence_ref ? `<div class="card-meta">${renderEvidence(metric.evidence_ref, sources, labels)}</div>` : ''}
      </div>
    </article>`).join('')}
  </aside>`;
}

export function renderReport(spec) {
  const labels = LABELS[spec.meta.locale] || LABELS.en;
  const sources = new Map(spec.sources.map((source) => [source.id, source]));
  const layoutReceipt = compileReportLayout(spec);
  const layoutBySection = new Map(layoutReceipt.sections.map((layout) => [layout.sectionId, layout]));
  const metaPills = [
    labels.archetypes[spec.meta.archetype] || spec.meta.archetype,
    labels.audiences[spec.meta.audience] || spec.meta.audience,
    spec.meta.updated_at,
    spec.meta.author,
  ].filter(Boolean);
  const nav = [
    ...spec.sections.map((section) => ({ id: section.id, title: section.title })),
    ...(spec.sources.length ? [{ id: 'sources', title: labels.sources }] : []),
  ];
  const metrics = renderMetrics(spec, sources, labels);
  const sourceHash = sha256Text(JSON.stringify(spec));

  const html = `<!doctype html>
<html lang="${escapeAttribute(spec.meta.locale)}" data-theme="${escapeAttribute(spec.meta.theme)}" data-quality-profile="${escapeAttribute(spec.meta.quality_profile)}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:; font-src 'none'; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'">
  <meta name="generator" content="Reportify 0.1.0">
  <meta name="reportify-source-sha256" content="${sourceHash}">
  <title>${escapeHtml(spec.meta.title)}</title>
  <style>${BASE_CSS}</style>
</head>
<body>
  <div class="report-shell">
    <div class="report-topbar">
      <nav class="report-nav" aria-label="Report sections">
        ${nav.map((entry) => `<a href="#${escapeAttribute(entry.id)}">${escapeHtml(entry.title)}</a>`).join('')}
      </nav>
      <div class="report-actions">
        <button class="icon-button" type="button" data-theme-toggle data-label-dark="${escapeAttribute(labels.dark)}" data-label-light="${escapeAttribute(labels.light)}">${escapeHtml(labels.dark)}</button>
        <button class="icon-button" type="button" data-print-report>${escapeHtml(labels.print)}</button>
      </div>
    </div>

    <main class="report-main">
      <header class="report-hero${metrics ? '' : ' no-metrics'}">
        <section class="hero-main" data-report-block data-geometry-box data-fill-policy="sparse-ok" data-audit-subject="hero-main">
          <div class="block-content" data-block-content>
            ${spec.meta.eyebrow ? `<p class="eyebrow">${escapeHtml(spec.meta.eyebrow)}</p>` : ''}
            <h1 data-check-text>${escapeHtml(spec.meta.title)}</h1>
            ${spec.meta.subtitle ? `<p class="hero-subtitle" data-check-text>${escapeHtml(spec.meta.subtitle)}</p>` : ''}
            ${metaPills.length ? `<div class="hero-meta">${metaPills.map((entry) => `<span class="meta-pill">${escapeHtml(entry)}</span>`).join('')}</div>` : ''}
            ${renderExecutive(spec, labels)}
          </div>
        </section>
        ${metrics}
      </header>

      ${spec.sections.map((section) => renderSection(section, layoutBySection.get(section.id), sources, labels)).join('')}
      ${renderSources(spec, labels)}
    </main>

    <footer class="report-footer">
      ${escapeHtml(labels.generated)} · ${escapeHtml(labels.visualPending)} · source ${sourceHash.slice(0, 12)}
    </footer>
  </div>

  <script id="reportify-source" type="application/json" class="audit-hidden">${jsonForHtml(spec)}</script>
  <script id="reportify-layout-receipt" type="application/json" class="audit-hidden">${jsonForHtml(layoutReceipt)}</script>
  <script>${RUNTIME_JS}</script>
</body>
</html>`;

  return { html, layoutReceipt, sourceHash };
}

export function checkRenderedHtml(html) {
  const errors = [];
  const warnings = [];
  const required = [
    '<!doctype html>',
    'data-quality-profile=',
    'id="reportify-source"',
    'id="reportify-layout-receipt"',
    'window.Reportify',
    'reportifyAuditReady',
  ];
  for (const needle of required) {
    if (!html.includes(needle)) errors.push({ code: 'MISSING_RENDER_CONTRACT', message: `Rendered HTML is missing ${needle}.` });
  }
  if (/\{\{[^}]+\}\}/.test(html)) errors.push({ code: 'PLACEHOLDER_CONTENT', message: 'Rendered HTML contains unresolved template placeholders.' });
  if (/<script\s+[^>]*src=|<link\s+[^>]*rel=["']stylesheet|@import\s+url/i.test(html)) {
    errors.push({ code: 'EXTERNAL_DEPENDENCY', message: 'Rendered HTML contains an external runtime dependency.' });
  }
  if (/^\s*\.report-card\s*\{[^}]*height:\s*100%/ms.test(html)) {
    warnings.push({ code: 'GLOBAL_EQUAL_HEIGHT_CARD', message: 'Ordinary report cards must not globally use height:100%.' });
  }
  return { valid: errors.length === 0, errors, warnings };
}
